[package]
name = "pixmap"
# When updating, also update the version in the workspace dependency in the root Cargo.toml
version = "0.0.9"
description = "A simple premultiplied RGBA8 pixmap type used by the Vello renderers."
categories = ["rendering", "graphics"]
keywords = ["2d", "vector-graphics"]
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[package.metadata.docs.rs]
all-features = true
# There are no platform specific docs.
default-target = "x86_64-unknown-linux-gnu"
targets = []

[dependencies]
bytemuck = { workspace = true, features = ["derive"] }
peniko = { workspace = true, features = ["bytemuck"] }
png = { workspace = true, optional = true }

[features]
# If adding new features, also document in `src/lib.rs`
default = ["std", "png"]
# Get floating point functions from the standard library (likely using your target's libc).
std = ["peniko/std"]
# Use floating point implementations from libm.
libm = ["peniko/libm"]
# Allow loading a Pixmap from PNG and encoding it back to PNG.
png = ["std", "dep:png"]

[lints]
workspace = true
